const myprojects = [
    {
        id: 1,
        title: "Hydraforce",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-1.png",
        link: "/",
    }, 
    {
        id: 2,
        title: "JAZYKY",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-2.png",
        link: "/",
    }, 
    {
        id: 3,
        title: "KWERTZ Theme",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-3.png",
        link: "/",
    }, 
    {
        id: 4,
        title: "Kyon",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-4.png",
        link: "/",
    }, 
    {
        id: 5,
        title: "La Forge",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-5.png",
        link: "/",
    }, 
    {
        id: 6,
        title: "Neiro",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-6.png",
        link: "/",
    }, 
    {
        id: 7,
        title: "Pawsitive",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-7.png",
        link: "/",
    }, 
    {
        id: 8,
        title: "A Portfolio Template",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-8.png",
        link: "/",
    }, 
    {
        id: 9,
        title: "Securezza",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-9.png",
        link: "/",
    }, 
    {
        id: 10,
        title: "SKVER Expo",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-10.png",
        link: "/",
    }, 
    {
        id: 11,
        title: "Verena Pelican",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-11.png",
        link: "/",
    }, 
    {
        id: 12,
        title: "WebIndustries",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-12.png",
        link: "/",
    }, 
    {
        id: 13,
        title: "Titanic Belfest",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-13.png",
        link: "/",
    }, 
    {
        id: 14,
        title: "Snapwear",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-14.png",
        link: "/",
    }, 
    {
        id: 15,
        title: "Clynxx",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-15.png",
        link: "/",
    }, 
    {
        id: 16,
        title: "GetALook",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-16.png",
        link: "/",
    }, 
    {
        id: 17,
        title: "Folkarts Rajasthan",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-17.png",
        link: "/",
    }, 
    {
        id: 18,
        title: "BillySol",
        tools: ["HTML", "SCSS", "JavaScript", "Bootstrap"],
        image: "./projects/project-18.png",
        link: "/",
    }, 
] 

export default myprojects;